name 'netmanagers-varnish'
version '2.1.1'

author  'Javier Bertoli'
license 'Apache2'
project_page 'http://www.netmanagers.com.ar'
source 'https://github.com/netmanagers/puppet-varnish'
summary 'Puppet module for varnish'
description 'This module installs and manages varnish. Check README for details.'
dependency 'puppetlabs/stdlib',  '>=2.2.0'
dependency 'example42/puppi',    '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor',  '>=2.0.0'
